train:
  _target_: src.datasets.LibrispeechDataset
  part: "train_all"
  max_audio_length: 20.0
  max_text_length: 350
  instance_transforms: ${transforms.instance_transforms.train}
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  max_audio_length: 20.0
  max_text_length: 350
  instance_transforms: ${transforms.instance_transforms.inference}
