train:
  spectrogram: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.spec_augs.TimeMaskingAug
        time_mask_param: 30
        p: 0.2
      - _target_: src.transforms.spec_augs.FrequencyMaskingAug
        freq_mask_param: 35
        p: 0.5
