defaults:
  - model: deepspeech
  - metrics: example
  - datasets: inference_custom_dataset
  - dataloader: example
  - transforms: example_only_instance
  - _self_
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: prediction # any name here, can be a dataset name
  seed: 1
  from_pretrained: src/model_weights/model_best.pth # path to the pretrained model
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  language_model_path: src/language_model/lm.arpa
  alphabet_path: src/language_model/lm_vocab.txt
